### ISSUE TITLE
CGO_ENABLED=1 makes cspc-operator can't run in alpine

### ISSUE THREAD

**Issue by wangzihao3** [openebs/maya#1568]
https://github.com/openebs/maya/blob/b779f95944259f453ffceb9bdf404cddcb54c057/buildscripts/build.sh#L91

When I want to use https://github.com/openebs/openebs/blob/master/k8s/cspc-operator.yaml to create `cspc-operator pod`. I replace the image with the one I built. But the container crashs and the log shows `standard_init_linux.go:190: exec user process caused "no such file or directory"`

Then I find that my go env set CGO_ENABLED=1 default. When I set CGO_ENABLED=0 and build again. The cspc-operator container can run well.

Maybe we should change this line `env GOOS=$GOOS GOARCH=$GOARCH go build ${BUILD_TAG} -ldflags \ ` to `env CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build ${BUILD_TAG} -ldflags \ ` ?

**Comment by kmova** [comment]
Hi @Wangzihao18 -- missed this issue. 

@sonasingh46 -- is there a dependency on CGO for CSPC?

**Comment by Wangzihao18** [comment]
Hi @kmova. Here is more information https://openebs-community.slack.com/archives/CKYEGHHDW/p1577438814008300.

**Comment by sonasingh46** [comment]
@Wangzihao18 -- Does the same problem happens with the OpenEBS tagged cspc-operator or only with the image you built by yourself?
Also, what is the node operating system where the pod was deployed? 
Plus, I do not think there are any cgo dependency with the cspc-operator.

**Comment by Wangzihao18** [comment]
Hi @sonasingh46. The problem only happens with the image built by myself.
The node's operating system is Ubuntu18.04.
I think it is not the problem of the cspc-operator but the base image. I use the alpine of ARM version as the base image. It seems that the ARM alpine misses some runtime environment. As @prateekpandey14 said, `in general above container error comes due to cross-compile issue, mostly I have seen in case of alpine base images, due to some required libs/pkg missing in alpine image`
So if I set `CGO_ENABLED=1` to compile the program dynamic. It would cause the error.

**Comment by kmova** [comment]
We have moved the builds to multi-arch builds. Please reopen if this is still an issue.
